#+ summary: Returns a list of suggested terms
#+ endpoint: http://data.dive.beeldengeluid.nl/sparql/
#+ idField: suggestion
#+ tags:
#+      - Dive-UI-DBPedia
SELECT ?suggestion WHERE {
  VALUES (?suggestion) {
   ("Marco Polo")
   ("Frida")
   ("Clinton")
   ("Obama")
  }
}
